### Health
GET http://localhost:3000/health

### List tasks
GET http://localhost:3000/tasks

### List tasks pages
GET http://localhost:3000/tasks?page=1&limit=2

### List tasks true
GET http://localhost:3000/tasks?done=false

### List tasks order
GET http://localhost:3000/tasks?page=1&limit=2&sort=updatedAt&order=desc

### List tasks done pages
GET http://localhost:3000/tasks?done=false&page=1&limit=2

### Create task
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "title": "Tarea con desc",
  "description": "esto es una descripción"
}



### Get task by id
GET http://localhost:3000/tasks/4

### Get non-existing task
GET http://localhost:3000/tasks/999

### Get invalid task id
GET http://localhost:3000/tasks/abc


### Update task title
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
  "title": "Tarea actualizada"
}

### Update task description
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
  "description": "nueva descripción"
}


### Mark task as done
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
  "done": true
}

### Invalid id
PUT http://localhost:3000/tasks/abc
Content-Type: application/json

{
  "done": true
}

### Non existing task
PUT http://localhost:3000/tasks/999
Content-Type: application/json

{
  "done": true
}

### Invalid done type
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
  "done": "yes"
}


### Delete existing task
DELETE http://localhost:3000/tasks/1

### Delete non-existing task
DELETE http://localhost:3000/tasks/999

### Delete invalid id
DELETE http://localhost:3000/tasks/abc

### List tasks after delete
GET http://localhost:3000/tasks

### Search tasks primera
GET http://localhost:3000/tasks?search=primera

### Search tasks tarea
GET http://localhost:3000/tasks?search=tarea

### Delete 2
DELETE http://localhost:3000/tasks/2

### List tasks
GET http://localhost:3000/tasks

### List tasks including deletes
GET http://localhost:3000/tasks?includeDeleted=true

### Return task
PATCH http://localhost:3000/tasks/2/restore

### Solo borradas
GET http://localhost:3000/tasks?onlyDeleted=true